Minor update

diff --git a/bin/update-everything b/bin/update-everything
--- a/bin/update-everything
+++ b/bin/update-everything
@@ -1,68 +1,68 @@
-#!/usr/bin/env bash
-
-set -euo pipefail
-
-# update: catch-all update script
-
-function installed() {
-	cmd=$(command -v "${1}")
-
-	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
-	return ${?}
-}
-
-function prompt {
-	echo -n "${1} (y/N): " && read ans
-	[[ "$ans" =~ [Yy] ]]
-	return ${?}
-}
-
-function do_snap {
-	sudo snap refresh
-}
-
-function do_apt {
-	sudo apt update
-	sudo apt upgrade
-	sudo apt dist-upgrade
-	sudo apt autoremove
-	sudo apt clean
-}
-
-function do_pacman {
-	sudo pacman -Syyu
-}
-
-function do_brew {
-	brew -v update
-	brew -v upgrade
-	brew cleanup -s
-}
-
-function do_cpan {
-	cpan -u
-}
-
-function do_pip {
-	# http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip
-	pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | sudo xargs -n1 pip install -U
-	pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | sudo xargs -n1 pip install -U
-}
-
-function do_gem {
-	gem update
-}
-
-function do_npm {
-	npm update
-}
-
-[[ "$(uname)" = "Linux" ]] && installed apt && do_apt
-[[ "$(uname)" = "Linux" ]] && installed snap && do_snap
-[[ "$(uname)" = "Linux" ]] && installed pacman && do_pacman
-installed brew && do_brew
-
-installed gem && prompt "Update gems?" && do_gem
-installed pip && prompt "Update Python packages?" && do_pip
-installed cpan && prompt "Update CPAN modules?" && do_cpan
-installed npm && prompt "Update NPM modules?" && do_npm
+# #!/usr/bin/env bash
+#
+# set -euo pipefail
+#
+# # update: catch-all update script
+#
+# function installed() {
+# 	cmd=$(command -v "${1}")
+#
+# 	[[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
+# 	return ${?}
+# }
+#
+# function prompt {
+# 	echo -n "${1} (y/N): " && read ans
+# 	[[ "$ans" =~ [Yy] ]]
+# 	return ${?}
+# }
+#
+# function do_snap {
+# 	sudo snap refresh
+# }
+#
+# function do_apt {
+# 	sudo apt update
+# 	sudo apt upgrade
+# 	sudo apt dist-upgrade
+# 	sudo apt autoremove
+# 	sudo apt clean
+# }
+#
+# function do_pacman {
+# 	sudo pacman -Syyu
+# }
+#
+# function do_brew {
+# 	brew -v update
+# 	brew -v upgrade
+# 	brew cleanup -s
+# }
+#
+# function do_cpan {
+# 	cpan -u
+# }
+#
+# function do_pip {
+# 	# http://stackoverflow.com/questions/2720014/upgrading-all-packages-with-pip
+# 	pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | sudo xargs -n1 pip install -U
+# 	pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | sudo xargs -n1 pip install -U
+# }
+#
+# function do_gem {
+# 	gem update
+# }
+#
+# function do_npm {
+# 	npm update
+# }
+#
+# [[ "$(uname)" = "Linux" ]] && installed apt && do_apt
+# [[ "$(uname)" = "Linux" ]] && installed snap && do_snap
+# [[ "$(uname)" = "Linux" ]] && installed pacman && do_pacman
+# installed brew && do_brew
+#
+# installed gem && prompt "Update gems?" && do_gem
+# installed pip && prompt "Update Python packages?" && do_pip
+# installed cpan && prompt "Update CPAN modules?" && do_cpan
+# installed npm && prompt "Update NPM modules?" && do_npm
